package service

import (
	"fmt"
	"html"
	"strings"
	"time"
)

// Every automatic e-mail is composed here, and nowhere else. The jobs call
// these to send and the preview endpoint calls them to render, so what the
// settings screen shows is the same text that actually goes out.

const emailDateLayout = "Jan 02, 2006"

// usDate turns the ISO dates that travel through the system into the format
// the people reading these e-mails actually use. Anything unparseable is left
// alone rather than replaced with a wrong date.
func usDate(value string) string {
	parsed, err := time.Parse("2006-01-02", strings.TrimSpace(value))
	if err != nil {
		return value
	}
	return parsed.Format("01/02/2006")
}

// EmailBody is a composed message minus its recipients.
type EmailBody struct {
	Subject string `json:"subject"`
	Text    string `json:"text"`
	HTML    string `json:"html"`
}

func emailTable(headers []string, rows [][]string) string {
	var out strings.Builder
	out.WriteString(`<table style="border-collapse:collapse;width:100%;font-size:14px">`)
	out.WriteString(`<thead><tr>`)
	for _, header := range headers {
		out.WriteString(`<th style="text-align:left;border-bottom:1px solid #ccc;padding:8px">` + html.EscapeString(header) + `</th>`)
	}
	out.WriteString(`</tr></thead><tbody>`)
	for _, row := range rows {
		out.WriteString(`<tr>`)
		for _, cell := range row {
			out.WriteString(`<td style="padding:8px;border-bottom:1px solid #eee">` + html.EscapeString(cell) + `</td>`)
		}
		out.WriteString(`</tr>`)
	}
	out.WriteString(`</tbody></table>`)
	return out.String()
}

// ── Fieldwire documents missing ───────────────────────────────────────────────

// ChecklistItem is one line of the "current steps" block: what it is and where
// it stands. Both forecast alerts print the whole checklist, not only what is
// missing — reading the e-mail should answer "how far is this job", not just
// "something is wrong".
type ChecklistItem struct {
	Name string
	// Done, Dispensed ou nenhum dos dois — pendente.
	Done      bool
	Dispensed bool
}

func (i ChecklistItem) StateLabel() string {
	switch {
	case i.Dispensed:
		return "Dispensed"
	case i.Done:
		return "Completed"
	default:
		return "Pending"
	}
}

// jobLabel names a job the way every alert subject and body names it:
// "Community - Lot 1". The unit alone repeats across sites.
func jobLabel(jobSite, unit string) string {
	label := strings.TrimSpace(jobSite)
	if unit = strings.TrimSpace(unit); unit != "" {
		if label == "" {
			label = unit
		} else {
			label += " - " + unit
		}
	}
	return label
}

// alertSubject is the one subject shape every forecast alert follows:
// "<module> | <alert> | <job>". The module comes first so the inbox groups by
// system before it groups by problem.
func alertSubject(module, alert, jobSite, unit string) string {
	return fmt.Sprintf("%s | %s | %s", module, alert, jobLabel(jobSite, unit))
}

// checklistBlocks renders the checklist twice — plain text and HTML — since
// every alert body carries both.
func checklistBlocks(items []ChecklistItem) (string, string) {
	var text, htmlOut strings.Builder
	htmlOut.WriteString(`<p style="margin-bottom:4px"><strong>Current steps:</strong></p><ul style="margin-top:0;padding-left:18px">`)
	for _, item := range items {
		state := item.StateLabel()
		text.WriteString(fmt.Sprintf("%s — %s\n", item.Name, state))
		color := "#b45309"
		if item.Done || item.Dispensed {
			color = "#15803d"
		}
		htmlOut.WriteString(fmt.Sprintf(
			`<li>%s — <span style="color:%s;font-weight:600">%s</span></li>`,
			html.EscapeString(item.Name), color, state))
	}
	htmlOut.WriteString(`</ul>`)
	return text.String(), htmlOut.String()
}

type FieldwireMissingProject struct {
	// JobSite is the community; Unit is the lot or building inside it. Both
	// are needed to identify a job: the unit number repeats across sites.
	JobSite        string
	Unit           string
	Address        string
	Client         string
	ReferenceLabel string
	ReferenceDate  time.Time
	TargetDate     time.Time
	Documents      []ChecklistItem
}

// FieldwireSubject is also what the delivery history shows, so both name a job
// the same way.
func FieldwireSubject(jobSite, unit string) string {
	return alertSubject("Framing Forecast", "Fieldwire Docs Missing", jobSite, unit)
}

func BuildFieldwireMissingEmail(project FieldwireMissingProject) EmailBody {
	subject := FieldwireSubject(project.JobSite, project.Unit)
	job := jobLabel(project.JobSite, project.Unit)
	checklistText, checklistHTML := checklistBlocks(project.Documents)

	intro := "This is an automatic alert generated by missing Fieldwire documents for a job approaching its " +
		strings.ToLower(project.ReferenceLabel) + "."

	text := fmt.Sprintf(
		"%s\n\nJob: %s\nAddress: %s\nClient: %s\n%s: %s\n\nCurrent steps:\n%s",
		intro, job, project.Address, project.Client,
		project.ReferenceLabel, project.ReferenceDate.Format(emailDateLayout),
		checklistText,
	)

	htmlBody := fmt.Sprintf(
		`<p>%s</p><p style="color:#555;font-size:13px">Job: <strong>%s</strong><br>Address: %s<br>Client: %s<br>%s: <strong>%s</strong></p>%s`,
		html.EscapeString(intro), html.EscapeString(job),
		html.EscapeString(project.Address), html.EscapeString(project.Client),
		html.EscapeString(project.ReferenceLabel), project.ReferenceDate.Format(emailDateLayout),
		checklistHTML,
	)

	return EmailBody{Subject: subject, Text: text, HTML: htmlBody}
}

// ── Workers' Compensation ─────────────────────────────────────────────────────

type WorkersCompRow struct {
	ContractorName string
	Divisions      string
}

// The list is what has to be checked, so every row is pending by definition —
// a status column would carry the same word on every line.
func BuildWorkersCompReviewEmail(reviewDate string, checks []WorkersCompRow) EmailBody {
	var textRows strings.Builder
	rows := make([][]string, 0, len(checks))
	for _, check := range checks {
		textRows.WriteString(fmt.Sprintf("- %s | %s\n", check.ContractorName, check.Divisions))
		rows = append(rows, []string{check.ContractorName, check.Divisions})
	}
	return EmailBody{
		Subject: "Workers' Compensation Review — " + usDate(reviewDate),
		Text:    "Review each eligible subcontractor below and record Regular or Irregular in BOR.\n\n" + textRows.String(),
		HTML: `<p>Review each eligible subcontractor below and record <strong>Regular</strong> or <strong>Irregular</strong> in BOR.</p>` +
			emailTable([]string{"Subcontractor", "Divisions"}, rows),
	}
}

// WorkersCompResultRow is one subcontractor as the cycle left it.
type WorkersCompResultRow struct {
	ContractorName string
	Divisions      string
	Notes          string
}

// The blocks read in the order the reader needs them: what demands action, then
// what was never answered, then what is fine. Pending is skipped when empty —
// nobody should be left unchecked, so its presence is itself the message.
func BuildWorkersCompResultEmail(reviewDate string, irregular, pending, regular []WorkersCompResultRow) EmailBody {
	blocks := []struct {
		title string
		rows  []WorkersCompResultRow
	}{
		{"Irregular", irregular},
		{"Not checked", pending},
		{"Regular", regular},
	}

	var text, htmlOut strings.Builder
	for _, block := range blocks {
		if len(block.rows) == 0 {
			continue
		}
		text.WriteString(fmt.Sprintf("%s (%d)\n", block.title, len(block.rows)))
		table := make([][]string, 0, len(block.rows))
		for _, row := range block.rows {
			line := fmt.Sprintf("- %s | %s", row.ContractorName, row.Divisions)
			if note := strings.TrimSpace(row.Notes); note != "" {
				line += " — " + note
			}
			text.WriteString(line + "\n")
			table = append(table, []string{row.ContractorName, row.Divisions, strings.TrimSpace(row.Notes)})
		}
		text.WriteString("\n")
		htmlOut.WriteString(fmt.Sprintf(`<h3 style="margin:16px 0 8px;font-size:15px">%s (%d)</h3>`,
			html.EscapeString(block.title), len(block.rows)))
		htmlOut.WriteString(emailTable([]string{"Subcontractor", "Divisions", "Notes"}, table))
	}

	total := len(irregular) + len(pending) + len(regular)
	if total == 0 {
		text.WriteString("No subcontractor was eligible for this cycle.\n")
		htmlOut.WriteString(`<p>No subcontractor was eligible for this cycle.</p>`)
	}

	return EmailBody{
		Subject: fmt.Sprintf("Workers' Compensation Result — %s (%d irregular)", usDate(reviewDate), len(irregular)),
		Text:    fmt.Sprintf("Result of the review opened on %s.\n\n%s", usDate(reviewDate), text.String()),
		HTML: fmt.Sprintf(`<p>Result of the review opened on <strong>%s</strong>.</p>`, html.EscapeString(usDate(reviewDate))) +
			htmlOut.String(),
	}
}

// ── Absence ───────────────────────────────────────────────────────────────────

type AbsenceRow struct {
	EmployeeName string
	TeamName     string
	DaysCount    int
	StartDate    string
}

func BuildAbsenceEmail(company string, alertDays int, events []AbsenceRow) EmailBody {
	label := strings.ToUpper(company)
	var textRows strings.Builder
	rows := make([][]string, 0, len(events))
	for _, event := range events {
		since := usDate(event.StartDate)
		textRows.WriteString(fmt.Sprintf("%s (%s) — %d business days, since %s\n",
			event.EmployeeName, event.TeamName, event.DaysCount, since))
		rows = append(rows, []string{event.EmployeeName, event.TeamName, fmt.Sprint(event.DaysCount), since})
	}
	subject := fmt.Sprintf("%s — %d employee(s) without clock-in", label, len(events))
	return EmailBody{
		Subject: subject,
		Text:    fmt.Sprintf("No punch for %d+ business days:\n\n%s", alertDays, textRows.String()),
		HTML: fmt.Sprintf(`<p>No clock-in was found for %d consecutive evaluated business days.</p>`, alertDays) +
			emailTable([]string{"Employee", "Team", "Days", "Since"}, rows),
	}
}

// ── Permit ────────────────────────────────────────────────────────────────────

// PermitPendingJob is one HVAC job about to start with Permit steps still open.
type PermitPendingJob struct {
	JobSite   string
	Unit      string
	Address   string
	StartDate time.Time
	Steps     []ChecklistItem
}

func PermitSubject(jobSite, unit string) string {
	return alertSubject("HVAC Forecast", "Permit Missing", jobSite, unit)
}

// BuildPermitPendingEmail composes one alert for one job, in the same shape as
// the Fieldwire alert: what triggered it, which job, when it starts, and where
// every step of the permit stands.
func BuildPermitPendingEmail(offsetDays int, job PermitPendingJob) EmailBody {
	subject := PermitSubject(job.JobSite, job.Unit)
	label := jobLabel(job.JobSite, job.Unit)
	checklistText, checklistHTML := checklistBlocks(job.Steps)

	intro := fmt.Sprintf(
		"This is an automatic alert generated by the incomplete permit issuance for a job starting within %d days.",
		offsetDays)

	text := fmt.Sprintf("%s\n\nJob: %s\nAddress: %s\nStart date: %s\n\nCurrent steps:\n%s",
		intro, label, job.Address, job.StartDate.Format(emailDateLayout), checklistText)

	htmlBody := fmt.Sprintf(
		`<p>%s</p><p style="color:#555;font-size:13px">Job: <strong>%s</strong><br>Address: %s<br>Start date: <strong>%s</strong></p>%s`,
		html.EscapeString(intro), html.EscapeString(label), html.EscapeString(job.Address),
		job.StartDate.Format(emailDateLayout), checklistHTML)

	return EmailBody{Subject: subject, Text: text, HTML: htmlBody}
}

// ── Preview samples ───────────────────────────────────────────────────────────

// previewSample builds each e-mail from invented data. The job is named in the
// text so nobody mistakes a preview for a real notification.
func previewSample(key string, cfg *TriggerConfig) EmailBody {
	sampleDate := time.Date(2026, time.October, 14, 0, 0, 0, 0, time.UTC)

	switch key {
	case TriggerForecastPlotPlan:
		months, days := 0, 0
		if cfg.ParamString("offset_unit", "months") == "months" {
			months = cfg.ParamInt("offset_value", 2)
		} else {
			days = cfg.ParamInt("offset_value", 60)
		}
		documents := cfg.ParamStrings("documents")
		if len(documents) == 0 {
			documents = []string{"Plot Plan", "Structural Plan"}
		}
		clients := cfg.ParamStrings("clients")
		client := "Toll Brothers"
		if len(clients) > 0 {
			client = clients[0]
		}
		checklist := make([]ChecklistItem, 0, len(documents))
		for index, document := range documents {
			checklist = append(checklist, ChecklistItem{Name: document, Done: index == 0 && len(documents) > 1})
		}
		return BuildFieldwireMissingEmail(FieldwireMissingProject{
			JobSite:        "SAMPLE — Willow Ridge at Sample, MA",
			Unit:           "Lot 128",
			Address:        "1420 Sample Ridge Dr, Sample City",
			Client:         client,
			ReferenceLabel: ReferenceLabel(cfg.ParamString("date_field", "previous_start_date")),
			ReferenceDate:  sampleDate,
			TargetDate:     sampleDate.AddDate(0, -months, -days),
			Documents:      checklist,
		})

	case TriggerWorkersCompReview:
		return BuildWorkersCompReviewEmail(sampleDate.Format(workersCompDateLayout), []WorkersCompRow{
			{ContractorName: "SAMPLE — Ace Drywall LLC", Divisions: "Framing"},
			{ContractorName: "SAMPLE — Northline Concrete", Divisions: "HVAC, PCG"},
		})

	case TriggerWorkersCompResult:
		return BuildWorkersCompResultEmail(sampleDate.Format(workersCompDateLayout),
			[]WorkersCompResultRow{
				{ContractorName: "SAMPLE — Northline Concrete", Divisions: "HVAC, PCG", Notes: "Policy expired 09/30"},
			},
			[]WorkersCompResultRow{
				{ContractorName: "SAMPLE — Ridge Framing Co", Divisions: "Framing"},
			},
			[]WorkersCompResultRow{
				{ContractorName: "SAMPLE — Ace Drywall LLC", Divisions: "Framing", Notes: "Certificate on file"},
			})

	case TriggerQBTimeAbsence:
		return BuildAbsenceEmail("framing", cfg.ParamInt("alert_days", 2), []AbsenceRow{
			{EmployeeName: "SAMPLE — John Carter", TeamName: "Framing Crew A", DaysCount: 2, StartDate: "2026-10-12"},
			{EmployeeName: "SAMPLE — Maria Lopes", TeamName: "Framing Crew B", DaysCount: 3, StartDate: "2026-10-09"},
		})

	case TriggerForecastPermit:
		return BuildPermitPendingEmail(cfg.ParamInt("offset_days", 30), PermitPendingJob{
			JobSite:   "SAMPLE — Willow Ridge at Sample, MA",
			Unit:      "Lot 128",
			Address:   "1420 Sample Ridge Dr, Sample City",
			StartDate: sampleDate,
			Steps: []ChecklistItem{
				{Name: "Manual J", Done: true},
				{Name: "Application Submitted", Done: true},
				{Name: "Permit Approved"},
			},
		})
	}
	return EmailBody{Subject: "No preview available", Text: "", HTML: "<p>No preview available for this trigger.</p>"}
}

func ReferenceLabel(field string) string {
	switch field {
	case "previous_beams_date":
		return "Beams date"
	case "previous_end_date":
		return "End date"
	default:
		return "Start date"
	}
}
