import {
  AirVent, Anchor, Antenna, Axe, Bath, Battery, Blend, Blinds, Blocks, Bolt, Box, Boxes,
  BrickWall, Brush, Building, Building2, Cable, Castle, Cctv, CloudRain, Cog, Columns3,
  Component, Cone, Construction, Container, Cylinder, DoorClosed, DoorOpen, Drill, Droplet,
  Droplets, Factory, Fan, Fence, Flame, Flower2, Frame, Fuel, Gauge, Grid2x2, Grid3x3, Hammer,
  HardHat, Hexagon, Hotel, House, HousePlug, Key, Lamp, LampCeiling, Landmark, Layers, Layers2,
  LayoutGrid, Leaf, Lightbulb, Lock, Magnet, Mountain, Nut, PaintBucket, Paintbrush,
  PaintbrushVertical, PaintRoller, PanelBottom, PanelsTopLeft, PanelTop, PencilRuler, Pickaxe,
  Plug, PlugZap, Pyramid, Refrigerator, Rows2, Rows3, Rows4, Ruler, ShieldCheck, ShowerHead,
  Shovel, Shrub, Signpost, Snowflake, Sofa, Sprout, SquareStack, Sun, Table, Tent, Thermometer,
  TrafficCone, TreeDeciduous, TreePine, Trees, Truck, Umbrella, Warehouse, WashingMachine,
  Waves, Wind, Wrench, Zap,
} from "lucide-react"

// Wide on purpose: an icon can only belong to one trade, so the catalog has to
// outrun the trade list by a good margin or new trades run out of options.
export const TRADE_ICONS = {
  foundation:   { icon: Blocks,             label: "Foundation" },
  excavation:   { icon: Shovel,             label: "Excavation" },
  framing:      { icon: Frame,              label: "Framing" },
  deck:         { icon: Fence,              label: "Deck / fence" },
  glass:        { icon: ShowerHead,         label: "Glass / shower" },
  landscaping:  { icon: Trees,              label: "Landscaping" },
  plumbing:     { icon: Droplets,           label: "Plumbing" },
  electrical:   { icon: Zap,                label: "Electrical" },
  hvac:         { icon: AirVent,            label: "HVAC" },
  insulation:   { icon: Layers,             label: "Insulation" },
  roofing:      { icon: House,              label: "Roofing" },
  gutters:      { icon: CloudRain,          label: "Gutters" },
  siding:       { icon: Rows3,              label: "Siding" },
  masonry:      { icon: BrickWall,          label: "Masonry" },
  drywall:      { icon: PanelsTopLeft,      label: "Drywall" },
  painting:     { icon: PaintRoller,        label: "Painting" },
  tile:         { icon: Grid2x2,            label: "Tile" },
  flooring:     { icon: Rows4,              label: "Flooring" },
  trim:         { icon: Ruler,              label: "Trim / finish" },
  general:      { icon: Hammer,             label: "General" },

  pickaxe:      { icon: Pickaxe,            label: "Demolition" },
  axe:          { icon: Axe,                label: "Carpentry" },
  hardhat:      { icon: HardHat,            label: "Site supervision" },
  construction: { icon: Construction,       label: "Construction" },
  wrench:       { icon: Wrench,             label: "Mechanical" },
  drill:        { icon: Drill,              label: "Drilling" },
  layout:       { icon: PencilRuler,        label: "Layout / survey" },
  brush:        { icon: Paintbrush,         label: "Fine painting" },
  brush_alt:    { icon: PaintbrushVertical, label: "Staining" },
  paint_bucket: { icon: PaintBucket,        label: "Coatings" },
  sweep:        { icon: Brush,              label: "Cleanup" },
  lighting:     { icon: Lightbulb,          label: "Lighting" },
  outlets:      { icon: Plug,               label: "Outlets" },
  service:      { icon: PlugZap,            label: "Electrical service" },
  low_voltage:  { icon: Cable,              label: "Low voltage" },
  ventilation:  { icon: Fan,                label: "Ventilation" },
  air_sealing:  { icon: Wind,               label: "Air sealing" },
  thermostat:   { icon: Thermometer,        label: "Controls" },
  gas:          { icon: Flame,              label: "Gas / fireplace" },
  refrigerant:  { icon: Snowflake,          label: "Refrigeration" },
  waterproof:   { icon: Waves,              label: "Waterproofing" },
  irrigation:   { icon: Droplet,            label: "Irrigation" },
  fixtures:     { icon: Bath,               label: "Bath fixtures" },
  sod:          { icon: Sprout,             label: "Sod / seeding" },
  trees_dec:    { icon: TreeDeciduous,      label: "Tree work" },
  trees_pine:   { icon: TreePine,           label: "Evergreens" },
  planting:     { icon: Flower2,            label: "Planting" },
  mulch:        { icon: Leaf,               label: "Mulch" },
  shrubs:       { icon: Shrub,              label: "Shrubs" },
  doors:        { icon: DoorOpen,           label: "Doors" },
  door_hw:      { icon: DoorClosed,         label: "Door hardware" },
  blinds:       { icon: Blinds,             label: "Blinds / shades" },
  lamps:        { icon: Lamp,               label: "Lamps" },
  ceiling:      { icon: LampCeiling,        label: "Ceiling fixtures" },
  furnishing:   { icon: Sofa,               label: "Furnishing" },
  appliances:   { icon: Refrigerator,       label: "Appliances" },
  laundry:      { icon: WashingMachine,     label: "Laundry" },
  security:     { icon: Cctv,               label: "Security" },
  alarm:        { icon: ShieldCheck,        label: "Fire / safety" },
  locks:        { icon: Key,                label: "Locksmith" },
  access:       { icon: Lock,               label: "Access control" },
  antenna:      { icon: Antenna,            label: "Antenna / comms" },
  signage:      { icon: Signpost,           label: "Signage" },
  traffic:      { icon: TrafficCone,        label: "Traffic control" },
  hauling:      { icon: Truck,              label: "Hauling" },
  dumpster:     { icon: Container,          label: "Dumpster" },
  materials:    { icon: Boxes,              label: "Materials" },
  crate:        { icon: Box,                label: "Crating" },
  warehouse:    { icon: Warehouse,          label: "Warehouse" },
  building:     { icon: Building,           label: "Commercial" },
  building_alt: { icon: Building2,          label: "Multifamily" },
  factory:      { icon: Factory,            label: "Industrial" },
  hotel:        { icon: Hotel,              label: "Hospitality" },
  castle:       { icon: Castle,             label: "Masonry / stone" },
  civic:        { icon: Landmark,           label: "Civic" },
  temporary:    { icon: Tent,               label: "Temporary structures" },
  house_plug:   { icon: HousePlug,          label: "Home systems" },
  solar:        { icon: Sun,                label: "Solar" },
  awning:       { icon: Umbrella,           label: "Awnings" },
  grading:      { icon: Mountain,           label: "Grading" },
  anchoring:    { icon: Anchor,             label: "Anchoring" },
  fasteners:    { icon: Nut,                label: "Fasteners" },
  bolts:        { icon: Bolt,               label: "Structural bolts" },
  metals:       { icon: Magnet,             label: "Metals" },
  battery:      { icon: Battery,            label: "Backup power" },
  fuel:         { icon: Fuel,               label: "Fuel" },
  metering:     { icon: Gauge,              label: "Metering" },
  formwork:     { icon: Cone,               label: "Formwork" },
  columns:      { icon: Cylinder,           label: "Columns" },
  roof_pitch:   { icon: Pyramid,            label: "Roof pitch" },
  panels:       { icon: Component,          label: "Panels" },
  modules:      { icon: SquareStack,        label: "Modular" },
  hex:          { icon: Hexagon,            label: "Hex tile" },
  grid:         { icon: Grid3x3,            label: "Grid ceiling" },
  layout_grid:  { icon: LayoutGrid,         label: "Layout grid" },
  cladding:     { icon: Columns3,           label: "Cladding" },
  decking:      { icon: Rows2,              label: "Decking" },
  countertop:   { icon: Table,              label: "Countertops" },
  soffit:       { icon: PanelTop,           label: "Soffit" },
  baseboard:    { icon: PanelBottom,        label: "Baseboard" },
  membrane:     { icon: Layers2,            label: "Membrane" },
  finish:       { icon: Blend,              label: "Finish blend" },
  machinery:    { icon: Cog,                label: "Machinery" },
} as const

export type TradeIconKey = keyof typeof TRADE_ICONS

export const TRADE_ICON_KEYS = Object.keys(TRADE_ICONS) as TradeIconKey[]

export function tradeIcon(key: TradeIconKey): React.ElementType {
  return TRADE_ICONS[key]?.icon ?? Hammer
}
