// Generated from PCG_Scope_Questionnaire_AllTrades.xlsx — the catalog PCG maintains
// by hand today. Seeds the editable catalog on first load; edits live in the store.
import type { Trade } from "./types"

export const TRADES_SEED: Trade[] = [
  {
    id: "foundation",
    name: "Foundation",
    code: null,
    icon: "foundation",
    hasBidForm: false,
    standardNote: "",
    questions: [
      { id: "q1", label: "Project type", type: "select", options: ["New Construction", "Addition", "Renovation"], hint: "", tag: null, needsQuantity: false },
      { id: "q2", label: "Basement", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q3", label: "Crawl space", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q4", label: "Slab on grade", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q5", label: "Attached garage", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q6", label: "Concrete stoops / steps", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q7", label: "Window wells", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q8", label: "Crawl space vents", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q9", label: "Special conditions / notes", type: "text", options: [], hint: "", tag: null, needsQuantity: false },
    ],
    workIncluded: [
      "Forming, pouring, and finishing of all concrete footings to the dimensions and depths specified in the structural drawings.",
      "Forming, pouring, and finishing of all foundation walls, piers, or grade beams as indicated on the structural drawings.",
      "Installation of all reinforcing steel (rebar) per structural engineer's specifications, including dowels, ties, and placement at required depth and spacing.",
      "Installation of anchor bolts, hold-downs, post bases, and all embedded structural hardware as specified in the structural drawings and per local building code.",
      "Placement and compaction of gravel or crushed stone base layer below slab as specified in the drawings.",
      "Installation of vapor barrier beneath slab on grade per code and manufacturer's requirements.",
      "Forming, pouring, and finishing of concrete slab on grade, including control joints at required intervals per structural specifications.",
      "Forming, pouring, and finishing of garage slab, basement floor slab, and any interior slabs as indicated on the drawings.",
      "Forming, pouring, and finishing of all concrete stoops, landings, and steps directly connected to the foundation system.",
      "Installation of all window well frames embedded in foundation walls as indicated on the drawings.",
      "Installation of foundation vents in crawl space foundations per code requirements.",
      "Snap tie hole patching and surface preparation of foundation walls after form removal.",
      "Form removal and cleanup of all forming materials, wire, stakes, and concrete debris upon completion.",
      "Protection of completed foundation work from weather, freeze-thaw cycles, and construction traffic until adequate curing.",
    ],
    exclusions: [

    ],
    responsibilityMatrix: [
      "GC provides: approved architectural and structural drawings, soils report, and geotechnical recommendations prior to mobilization.",
      "Concrete supply: GC or Sub — to be defined at contract execution per Exhibit A.",
      "Rebar, anchor bolts, embedded hardware, vapor barrier, and gravel: GC or Sub — to be defined at contract execution per Exhibit A.",
      "GC provides: concrete pump truck if required by site conditions or pour volume.",
      "GC provides: building permit and coordination of all required foundation inspections.",
      "GC coordinates: backfill and compaction operations to follow foundation completion.",
      "Sub provides: all labor, supervision, forming systems, shoring, bracing, tools, and equipment.",
      "Sub provides: layout and elevation control for all foundation elements.",
      "GC coordinates: with all MEP subcontractors prior to each pour to confirm sleeve, conduit, and penetration locations.",
    ],
  },
  {
    id: "excavation",
    name: "Excavation",
    code: null,
    icon: "excavation",
    hasBidForm: false,
    standardNote: "",
    questions: [
      { id: "q1", label: "Project type", type: "select", options: ["New Construction", "Addition", "Renovation"], hint: "", tag: null, needsQuantity: false },
      { id: "q2", label: "Basement excavation", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q3", label: "Utility trenches", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q4", label: "Dewatering required", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q5", label: "Rock excavation", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "priced separately", tag: null, needsQuantity: false },
      { id: "q6", label: "Haul-off excess soil", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "priced separately", tag: null, needsQuantity: false },
      { id: "q7", label: "Engineered fill required", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q8", label: "Silt fence / erosion control", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q9", label: "Special conditions / notes", type: "text", options: [], hint: "", tag: null, needsQuantity: false },
    ],
    workIncluded: [
      "Mobilization and setup of all excavation equipment and temporary erosion control measures.",
      "Clearing and stripping of topsoil within the building footprint and construction zone.",
      "Mass excavation of the building footprint to the depths required for foundation, footing, and basement construction.",
      "Excavation of all individual footing pits, grade beam trenches, and stepped footings.",
      "Excavation of all utility trenches for water, sewer, gas, electrical, and drainage lines.",
      "Rock excavation if encountered — scope and pricing TBD per site conditions.",
      "Dewatering of excavation if groundwater is encountered.",
      "Shoring, sheeting, or slope stabilization as required by site conditions and OSHA regulations.",
      "Subgrade preparation and compaction to the bearing capacity specified by the geotechnical engineer.",
      "Import and placement of engineered fill or crushed stone as required.",
      "Rough grading of the site to direct surface water away from the building during construction.",
      "Backfill of all foundation walls after waterproofing is complete and approved.",
      "Backfill and compaction of all utility trenches after MEP rough-in inspections are complete.",
      "Final rough grading of the site in preparation for landscaping.",
      "Haul-off and legal disposal of all excess soil, rock, and debris — scope TBD per site conditions.",
      "Installation and maintenance of silt fence and stormwater pollution prevention measures.",
    ],
    exclusions: [

    ],
    responsibilityMatrix: [
      "GC provides: approved site plan, civil drawings, grading plan, and geotechnical/soils report prior to mobilization.",
      "GC provides: utility locating coordination and Dig Safe / 811 notification prior to excavation commencement.",
      "GC provides: building permit and coordination of all required inspections.",
      "Sub provides: all labor, supervision, excavation equipment, trucks, and tools.",
      "GC coordinates: with Foundation subcontractor to confirm excavation depths and subgrade bearing conditions.",
      "GC coordinates: with all MEP subcontractors to confirm trench locations, depths, and sequencing.",
      "GC coordinates: waterproofing inspection and approval prior to backfill of foundation walls.",
      "Staking and layout of excavation limits — responsibility of Licensed Surveyor, coordinated by GC.",
    ],
  },
  {
    id: "framing",
    name: "Framing",
    code: null,
    icon: "framing",
    hasBidForm: false,
    standardNote: "",
    questions: [
      { id: "q1", label: "Number of stories", type: "select", options: ["1", "1.5 Cape", "2", "2.5", "3"], hint: "", tag: null, needsQuantity: false },
      { id: "q2", label: "Basement framing", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q3", label: "Attached garage", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q4", label: "Screened porch", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q5", label: "Deck / porch framing", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q6", label: "Vaulted / cathedral ceilings", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q7", label: "Front porch framing", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q8", label: "Temporary construction stair", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q9", label: "Crane required", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "priced separately", tag: null, needsQuantity: false },
      { id: "q10", label: "Windows & exterior doors install", type: "yn", options: ["Yes"], hint: "included in Framing scope", tag: null, needsQuantity: false },
      { id: "q11", label: "Special conditions / notes", type: "text", options: [], hint: "", tag: null, needsQuantity: false },
    ],
    workIncluded: [
      "Framing of all interior and exterior walls, partitions, headers, and bearing assemblies per project drawings and building codes.",
      "Installation of wall and roof sheathing, including all blocking, nailers, and fastening per structural requirements.",
      "Installation of all windows and exterior doors, including shimming, leveling, fastening, and flashing integration.",
      "Stair framing for all interior and exterior stair assemblies, including stringers, landings, and structural members.",
      "Installation of all structural hardware furnished by GC, including joist hangers, straps, hold-downs, post bases, and hurricane ties.",
      "Coordination and framing of all rough openings for MEP trades, including headers, cripples, and blocking.",
      "Crane or lifting equipment if required — TBD per project requirements.",
      "Continuous site cleanup and removal of all framing-related debris, cutoffs, scrap lumber, and waste materials.",
      "One-year workmanship warranty commencing upon substantial completion.",
      "Coordination with GC and other trades to maintain project schedule.",
      "Labor to frame the front porch, including all pressure-treated deck framing members.",
      "Labor to build and install temporary construction stair through garage.",
      "Labor to frame basement walls, including rough openings for bulkhead access door.",
      "Labor to install fascia trim.",
    ],
    exclusions: [

    ],
    responsibilityMatrix: [
      "GC provides: all framing lumber, engineered wood, sheathing, structural hardware, windows, exterior doors, fasteners, and all materials — delivered in advance.",
      "GC provides: building permit, approved construction documents, and engineered structural drawings on-site prior to mobilization.",
      "GC coordinates: all required municipal framing inspections.",
      "Sub provides: all labor, supervision, hand tools, power tools, crane/lifting equipment, and consumables.",
      "GC coordinates: with MEP subcontractors to confirm rough opening sizes, backing locations, and penetration requirements.",
    ],
  },
  {
    id: "deck-and-porch",
    name: "Deck & Porch",
    code: null,
    icon: "deck",
    hasBidForm: false,
    standardNote: "",
    questions: [
      { id: "q1", label: "Deck / porch type", type: "select", options: ["Attached Deck", "Screened Porch", "Front Porch", "Covered Porch", "Multiple"], hint: "", tag: null, needsQuantity: false },
      { id: "q2", label: "Decking material", type: "select", options: ["Pressure-Treated", "Composite", "Hardwood", "Other"], hint: "", tag: null, needsQuantity: false },
      { id: "q3", label: "Number of levels", type: "select", options: ["1", "2", "Multiple"], hint: "", tag: null, needsQuantity: false },
      { id: "q4", label: "Stairs included", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q5", label: "Railing included", type: "yn", options: ["Yes", "No"], hint: "by Interior Trim sub", tag: null, needsQuantity: false },
      { id: "q6", label: "Screened porch enclosure", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q7", label: "Concrete footings / piers", type: "yn", options: ["Yes", "No"], hint: "by Foundation sub", tag: null, needsQuantity: false },
      { id: "q8", label: "Special conditions / notes", type: "text", options: [], hint: "", tag: null, needsQuantity: false },
    ],
    workIncluded: [
      "Installation of all structural framing for deck or porch, including posts, beams, joists, and ledger board connection to the house.",
      "Installation of all post bases, hardware, and connections per structural drawings and code requirements.",
      "Installation of all decking boards, including fastening, spacing, and end treatments per manufacturer's specifications.",
      "Installation of all stair stringers, treads, and risers.",
      "Installation of all perimeter framing, blocking, and fascia boards.",
      "Installation of all deck flashing at ledger and all penetrations to prevent water infiltration.",
      "Installation of all blocking and backing for railing posts.",
      "Site cleanup and removal of all deck-related materials and debris.",
    ],
    exclusions: [
      "Railing installation is excluded — performed by Interior Trim subcontractor.",
      "Concrete footings and piers for deck posts are excluded — performed by Foundation subcontractor.",
      "Painting or staining is excluded — performed by Painting subcontractor.",
      "Building permit and all required inspections are excluded — obtained and coordinated by GC.",
    ],
    responsibilityMatrix: [
      "GC provides: approved deck drawings and specifications prior to mobilization.",
      "Decking materials, framing lumber, hardware, and accessories: GC or Sub — to be defined at contract execution per Exhibit A.",
      "GC provides: building permit and coordination of all required inspections.",
      "Sub provides: all labor, supervision, tools, and equipment.",
      "Sub coordinates: with Interior Trim subcontractor for post blocking and anchor requirements.",
      "Sub coordinates: with Foundation subcontractor for footing installation prior to framing.",
    ],
  },
  {
    id: "shower-glass-and-mirrors",
    name: "Shower Glass & Mirrors",
    code: null,
    icon: "glass",
    hasBidForm: false,
    standardNote: "",
    questions: [
      { id: "q1", label: "Frameless shower enclosures", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: true },
      { id: "q2", label: "Semi-frameless enclosures", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: true },
      { id: "q3", label: "Tub enclosure / tub door", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: true },
      { id: "q4", label: "Bathroom mirrors", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "per bath", tag: null, needsQuantity: true },
      { id: "q5", label: "Mirror walls", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q6", label: "Glass shelving", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q7", label: "Hardware finish", type: "select", options: ["Chrome", "Brushed Nickel", "Matte Black", "Brushed Gold", "Other"], hint: "", tag: null, needsQuantity: false },
      { id: "q8", label: "Special conditions / notes", type: "text", options: [], hint: "", tag: null, needsQuantity: false },
    ],
    workIncluded: [
      "Templating and measuring of all shower enclosures prior to fabrication.",
      "Fabrication and installation of all frameless glass shower enclosures, including panels, doors, hinges, handles, and seals.",
      "Installation of all semi-frameless and framed shower enclosures if specified.",
      "Installation of all glass shower panels and tub enclosures.",
      "Installation of all bathroom mirrors, including frameless and framed mirrors.",
      "Installation of all mirror walls and glass shelving if specified.",
      "Site cleanup and removal of all glass-related materials and packaging.",
    ],
    exclusions: [
      "Tile and waterproofing installation are excluded — performed by Tile subcontractor.",
      "Plumbing fixture installation is excluded — performed by Plumbing subcontractor.",
      "Building permit and all required inspections are excluded — obtained and coordinated by GC.",
    ],
    responsibilityMatrix: [
      "GC provides: approved shower enclosure specifications, glass type, and hardware selections prior to templating.",
      "Sub provides: all fabrication, materials, labor, supervision, tools, and equipment.",
      "Sub coordinates: with Tile subcontractor to confirm tile installation is complete and walls are plumb and flat prior to templating.",
      "Sub coordinates: with Plumbing subcontractor to confirm all fixtures are installed prior to glass enclosure installation.",
    ],
  },
  {
    id: "landscaping",
    name: "Landscaping",
    code: null,
    icon: "landscaping",
    hasBidForm: false,
    standardNote: "",
    questions: [
      { id: "q1", label: "Final grading full lot", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q2", label: "Topsoil depth", type: "text", options: [], hint: "e.g. 4 inches", tag: null, needsQuantity: false },
      { id: "q3", label: "Sod", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q4", label: "Seeding", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q5", label: "Shrubs and plantings per plan", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q6", label: "Mulch beds and edging", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q7", label: "Drainage swales / French drains", type: "yn", options: ["Yes", "No", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q8", label: "Irrigation system", type: "yn", options: ["Yes", "No"], hint: "TBD bid form", tag: null, needsQuantity: false },
      { id: "q9", label: "Supply responsibility", type: "select", options: ["Labor Only — GC Supplies", "Sub Supplies All", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q10", label: "Special conditions / notes", type: "text", options: [], hint: "", tag: null, needsQuantity: false },
    ],
    workIncluded: [
      "Final grading of entire lot to achieve positive drainage away from the building.",
      "Installation and spreading of topsoil to the specified depth over all lawn areas.",
      "Installation of sod over all specified lawn areas.",
      "Seeding of all specified areas with specified seed mix.",
      "Installation of all shrubs, plants, and plantings per the approved landscape plan.",
      "Installation of all mulch beds, edging, and landscape borders.",
      "Installation of all drainage swales, French drains, and surface drainage features.",
      "Grading and seeding of all disturbed areas around the house perimeter.",
      "Site cleanup and removal of all construction debris, rocks, and excess soil.",
      "One-year warranty on all plant material and sod.",
    ],
    exclusions: [
      "Irrigation system installation is excluded unless specifically included herein.",
      "Hardscape installation is excluded unless specifically included herein.",
      "Tree removal beyond construction clearing is excluded unless specifically included herein.",
      "Building permit and all required inspections are excluded — obtained and coordinated by GC.",
    ],
    responsibilityMatrix: [
      "GC provides: approved grading plan, landscape plan, and final grade elevations prior to mobilization.",
      "Topsoil, sod, seed, plants, mulch, and materials: GC or Sub — to be defined at contract execution per Exhibit A.",
      "GC provides: building permit and coordination of all required inspections.",
      "Sub provides: all labor, supervision, equipment, tools, and machinery.",
      "GC coordinates: final utility locating and as-built survey prior to final grading.",
    ],
  },
  {
    id: "plumbing",
    name: "Plumbing",
    code: "BRF-PLB",
    icon: "plumbing",
    hasBidForm: true,
    standardNote: "",
    questions: [
      { id: "q1", label: "Water source", type: "select", options: ["City Water", "Well"], hint: "", tag: null, needsQuantity: false },
      { id: "q2", label: "Sewer", type: "select", options: ["Municipal Sewer", "Septic System"], hint: "", tag: null, needsQuantity: false },
      { id: "q3", label: "Gas", type: "select", options: ["Natural Gas", "Propane", "None"], hint: "", tag: null, needsQuantity: false },
      { id: "q4", label: "Main shutoff location", type: "text", options: [], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q5", label: "Outdoor hose bibs", type: "text", options: [], hint: "Qty & locations — per code", tag: null, needsQuantity: false },
      { id: "q6", label: "Water heater model / brand", type: "text", options: [], hint: "e.g. HTP Crossover 20-100", tag: null, needsQuantity: false },
      { id: "q7", label: "Water heater quantity", type: "select", options: ["1", "2", "3+"], hint: "", tag: null, needsQuantity: false },
      { id: "q8", label: "Water heater location", type: "text", options: [], hint: "e.g. Basement mechanical room", tag: null, needsQuantity: false },
      { id: "q9", label: "Furnace quantity", type: "select", options: ["1", "2", "3+"], hint: "", tag: null, needsQuantity: false },
      { id: "q10", label: "Furnace locations", type: "text", options: [], hint: "e.g. Basement + attic", tag: null, needsQuantity: false },
      { id: "q11", label: "Condensate drain required", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q12", label: "Fixture portfolio", type: "select", options: ["Attached", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q13", label: "Appliance connections", type: "multi", options: ["Dishwasher", "Refrigerator Shut-Off", "Ice Maker", "Washer Supply & Drain", "Wine Cooler", "Bar Sink", "Utility Sink", "Steam Shower Generator"], hint: "", tag: null, needsQuantity: false },
      { id: "q14", label: "Washer location", type: "select", options: ["1st Floor", "2nd Floor", "Basement", "Multiple"], hint: "", tag: null, needsQuantity: false },
      { id: "q15", label: "Supply responsibility", type: "select", options: ["PCG Supplies — Sub Installs", "Sub Supplies and Installs"], hint: "", tag: null, needsQuantity: false },
      { id: "q16", label: "Gas lines — interior", type: "multi", options: ["Range", "Cooktop", "Dryer", "Fireplace Interior", "HVAC", "Water Heater"], hint: "", tag: null, needsQuantity: false },
      { id: "q17", label: "Gas lines — exterior", type: "multi", options: ["Outdoor Grill", "Exterior Fireplace", "Generator (future)", "Outdoor Kitchen"], hint: "", tag: null, needsQuantity: false },
      { id: "q18", label: "Floor drains locations", type: "multi", options: ["Garage", "Basement", "Mechanical Room", "Laundry", "Mudroom"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q19", label: "Rinsing station", type: "select", options: ["Yes — Location Defined", "Yes — Location to Be Defined", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q20", label: "Basement bath rough", type: "select", options: ["Yes — Location Defined", "Rough Only to Be Defined", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q21", label: "Sump pump", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q22", label: "Steam shower", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q23", label: "Pot filler", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q24", label: "Water filter / softener", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q25", label: "Pool / hot tub connections", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q26", label: "Scope phase", type: "select", options: ["Rough-In Only", "Finish Only", "Both Phases"], hint: "", tag: null, needsQuantity: false },
      { id: "q27", label: "Materials", type: "select", options: ["Labor Only — PCG Supplies All", "Sub Supplies and Installs"], hint: "", tag: null, needsQuantity: false },
    ],
    workIncluded: [

    ],
    exclusions: [

    ],
    responsibilityMatrix: [

    ],
  },
  {
    id: "electrical",
    name: "Electrical",
    code: "BRF-ELC",
    icon: "electrical",
    hasBidForm: true,
    standardNote: "",
    questions: [
      { id: "q1", label: "Electrical service", type: "select", options: ["200 Amp", "400 Amp"], hint: "", tag: null, needsQuantity: false },
      { id: "q2", label: "Sub-panels", type: "text", options: [], hint: "Qty & locations", tag: null, needsQuantity: false },
      { id: "q3", label: "Whole house surge protector", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q4", label: "Furnaces / air handlers", type: "text", options: [], hint: "Qty & locations", tag: null, needsQuantity: false },
      { id: "q5", label: "Condensers / heat pumps", type: "text", options: [], hint: "Qty & locations", tag: null, needsQuantity: false },
      { id: "q6", label: "Tankless water heater", type: "text", options: [], hint: "Qty", tag: null, needsQuantity: false },
      { id: "q7", label: "Fixture portfolio", type: "select", options: ["Attached", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q8", label: "Range / stove", type: "select", options: ["Gas — Circuit Only", "Electric"], hint: "dedicated circuit", tag: null, needsQuantity: false },
      { id: "q9", label: "Range hood", type: "select", options: ["Gas — Circuit Only", "Electric"], hint: "dedicated circuit", tag: null, needsQuantity: false },
      { id: "q10", label: "Dryer", type: "select", options: ["Gas — Circuit Only", "Electric"], hint: "dedicated circuit", tag: null, needsQuantity: false },
      { id: "q11", label: "Fireplace", type: "select", options: ["Gas — Circuit Only", "Electric — Dedicated Circuit", "N/A"], hint: "", tag: null, needsQuantity: false },
      { id: "q12", label: "Car charger / EV", type: "text", options: [], hint: "Qty — Level 2 240V", tag: "all_projects", needsQuantity: false },
      { id: "q13", label: "Generator", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q14", label: "Solar panel chase", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q15", label: "Pool / hot tub circuit", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q16", label: "Recessed lights", type: "text", options: [], hint: "Qty — dimmer yes/no", tag: null, needsQuantity: false },
      { id: "q17", label: "Motion lights exterior", type: "text", options: [], hint: "Qty — locations TBD", tag: null, needsQuantity: false },
      { id: "q18", label: "Motion lights closets", type: "text", options: [], hint: "Qty", tag: "all_projects", needsQuantity: false },
      { id: "q19", label: "Under cabinet lights", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q20", label: "Towel warmers primary baths", type: "text", options: [], hint: "Qty — optional", tag: "optional", needsQuantity: false },
      { id: "q21", label: "Pre-wire landscape lighting", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q22", label: "Exterior soffit lighting", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q23", label: "Step / stair lighting", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q24", label: "Heated floor primary bath 1", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q25", label: "Heated floor primary bath 2", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q26", label: "Heated floor other locations", type: "text", options: [], hint: "", tag: "optional", needsQuantity: false },
      { id: "q27", label: "TV outlets RG6 each bedroom", type: "yn", options: ["Yes"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q28", label: "TV outlets great room", type: "yn", options: ["Yes"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q29", label: "TV outlets screened porch", type: "yn", options: ["Yes"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q30", label: "Garage door low voltage", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q31", label: "Doorbell / video intercom", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q32", label: "Smart panel", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q33", label: "Lutron / smart dimmer", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q34", label: "Toilet seat outlets", type: "text", options: [], hint: "Qty", tag: "all_projects", needsQuantity: false },
      { id: "q35", label: "Irrigation controller circuit", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q36", label: "Outdoor refrigerator circuit", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q37", label: "Smoke detectors", type: "text", options: [], hint: "Qty per code", tag: "all_projects", needsQuantity: false },
      { id: "q38", label: "CO detectors", type: "text", options: [], hint: "Qty per code", tag: "all_projects", needsQuantity: false },
      { id: "q39", label: "Bathroom exhaust fans", type: "text", options: [], hint: "Qty", tag: "all_projects", needsQuantity: false },
      { id: "q40", label: "GFCI protection", type: "multi", options: ["Bathrooms", "Kitchen", "Exterior", "Garage", "Basement"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q41", label: "AFCI protection", type: "text", options: [], hint: "Per code — all required circuits", tag: null, needsQuantity: false },
      { id: "q42", label: "Scope phase", type: "select", options: ["Rough-In Only", "Finish Only", "Both Phases"], hint: "", tag: null, needsQuantity: false },
      { id: "q43", label: "Fixtures / devices supply", type: "select", options: ["PCG Supplies — Sub Installs", "Sub Supplies and Installs"], hint: "", tag: null, needsQuantity: false },
      { id: "q44", label: "Materials / wire", type: "select", options: ["Labor Only — PCG Supplies", "Sub Supplies and Installs"], hint: "", tag: null, needsQuantity: false },
    ],
    workIncluded: [

    ],
    exclusions: [

    ],
    responsibilityMatrix: [

    ],
  },
  {
    id: "hvac",
    name: "HVAC",
    code: "BRF-HVC",
    icon: "hvac",
    hasBidForm: true,
    standardNote: "",
    questions: [
      { id: "q1", label: "Furnace quantity", type: "select", options: ["1", "2", "3+"], hint: "", tag: null, needsQuantity: false },
      { id: "q2", label: "Furnace unit 1 BTU", type: "select", options: ["60,000 BTU", "80,000 BTU", "100,000 BTU", "Other"], hint: "", tag: null, needsQuantity: false },
      { id: "q3", label: "Furnace unit 2 BTU", type: "select", options: ["60,000 BTU", "80,000 BTU", "100,000 BTU", "N/A"], hint: "", tag: null, needsQuantity: false },
      { id: "q4", label: "Furnace unit 3 BTU", type: "select", options: ["60,000 BTU", "80,000 BTU", "100,000 BTU", "N/A"], hint: "", tag: null, needsQuantity: false },
      { id: "q5", label: "Condenser quantity", type: "select", options: ["1", "2", "3+"], hint: "", tag: null, needsQuantity: false },
      { id: "q6", label: "Condenser unit 1 tonnage", type: "select", options: ["2 Ton", "2.5 Ton", "3 Ton", "3.5 Ton", "4 Ton", "5 Ton"], hint: "", tag: null, needsQuantity: false },
      { id: "q7", label: "Condenser unit 2 tonnage", type: "select", options: ["2 Ton", "2.5 Ton", "3 Ton", "3.5 Ton", "4 Ton", "5 Ton", "N/A"], hint: "", tag: null, needsQuantity: false },
      { id: "q8", label: "Condenser unit 3 tonnage", type: "select", options: ["2 Ton", "2.5 Ton", "3 Ton", "N/A"], hint: "", tag: null, needsQuantity: false },
      { id: "q9", label: "Number of zones", type: "select", options: ["1", "2", "3", "4", "5+"], hint: "", tag: null, needsQuantity: false },
      { id: "q10", label: "Zone descriptions", type: "text", options: [], hint: "Zone 1, Zone 2, Zone 3...", tag: null, needsQuantity: false },
      { id: "q11", label: "Bathroom exhaust fans tie-in", type: "text", options: [], hint: "Qty", tag: "all_projects", needsQuantity: false },
      { id: "q12", label: "Kitchen hood tie-in", type: "select", options: ["Ducted to Exterior", "Recirculating"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q13", label: "Whole-house humidifier", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q14", label: "Media filter / air purifier", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q15", label: "UV light sanitizer", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q16", label: "Conditioned screened porch", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q17", label: "Basement HVAC", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q18", label: "Garage heat", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q19", label: "Special conditions / notes", type: "text", options: [], hint: "", tag: null, needsQuantity: false },
    ],
    workIncluded: [

    ],
    exclusions: [

    ],
    responsibilityMatrix: [

    ],
  },
  {
    id: "insulation",
    name: "Insulation",
    code: "BRF-INS",
    icon: "insulation",
    hasBidForm: true,
    standardNote: "",
    questions: [
      { id: "q1", label: "HERS score target", type: "text", options: [], hint: "e.g. 55 or lower", tag: null, needsQuantity: false },
      { id: "q2", label: "Energy code", type: "select", options: ["IECC 2021", "IECC 2018", "State Code"], hint: "", tag: null, needsQuantity: false },
      { id: "q3", label: "HERS rater provided by", type: "select", options: ["PCG", "Sub Coordinates"], hint: "", tag: null, needsQuantity: false },
      { id: "q4", label: "Exterior walls insulation type", type: "select", options: ["Batt", "Spray Foam", "Rigid Board", "Combo"], hint: "", tag: null, needsQuantity: false },
      { id: "q5", label: "Exterior walls R-value", type: "text", options: [], hint: "", tag: null, needsQuantity: false },
      { id: "q6", label: "Attic insulation type", type: "select", options: ["Blown-In", "Batt", "Spray Foam"], hint: "", tag: null, needsQuantity: false },
      { id: "q7", label: "Attic R-value", type: "text", options: [], hint: "", tag: null, needsQuantity: false },
      { id: "q8", label: "Cathedral / vaulted ceilings", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q9", label: "Basement walls", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q10", label: "Rim joist", type: "select", options: ["Spray Foam", "Rigid Board", "Batt"], hint: "", tag: null, needsQuantity: false },
      { id: "q11", label: "Crawl space", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q12", label: "Garage ceiling — conditioned above", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q13", label: "Sound insulation interior walls", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q14", label: "Vapor barrier", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q15", label: "Materials supply", type: "select", options: ["Labor Only — PCG Supplies", "Sub Supplies and Installs"], hint: "", tag: null, needsQuantity: false },
    ],
    workIncluded: [

    ],
    exclusions: [

    ],
    responsibilityMatrix: [

    ],
  },
  {
    id: "roofing",
    name: "Roofing",
    code: "BRF-ROF",
    icon: "roofing",
    hasBidForm: true,
    standardNote: "",
    questions: [
      { id: "q1", label: "Roofing material type", type: "select", options: ["Architectural Shingles", "Metal", "Flat TPO", "Cedar Shake", "Slate"], hint: "", tag: null, needsQuantity: false },
      { id: "q2", label: "Brand / product line", type: "text", options: [], hint: "e.g. GAF Timberline HDZ", tag: null, needsQuantity: false },
      { id: "q3", label: "Color", type: "text", options: [], hint: "e.g. Charcoal", tag: null, needsQuantity: false },
      { id: "q4", label: "Warranty", type: "select", options: ["25 Year", "30 Year", "50 Year", "Lifetime"], hint: "", tag: null, needsQuantity: false },
      { id: "q5", label: "Underlayment", type: "select", options: ["Synthetic Felt", "30# Felt", "Self-Adhered"], hint: "", tag: null, needsQuantity: false },
      { id: "q6", label: "Ice & water shield", type: "multi", options: ["Eaves", "Valleys", "All Penetrations"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q7", label: "Drip edge", type: "select", options: ["Yes Aluminum", "Yes Steel", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q8", label: "Step flashing", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q9", label: "Counter flashing", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q10", label: "Pipe boot flashings", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q11", label: "Valley flashing", type: "select", options: ["Open Valley", "Closed Valley", "W-Metal Valley"], hint: "", tag: null, needsQuantity: false },
      { id: "q12", label: "Chimney flashing", type: "select", options: ["Yes Included", "Coordinated with Masonry Sub"], hint: "", tag: null, needsQuantity: false },
      { id: "q13", label: "Ridge vent", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q14", label: "Roof complexity", type: "select", options: ["Simple Gable", "Hip Roof", "Complex Multiple Planes"], hint: "", tag: null, needsQuantity: false },
      { id: "q15", label: "Screened porch roof", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q16", label: "Garage roof included", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q17", label: "Sheathing replacement", type: "select", options: ["Sub Responsibility", "PCG to Authorize Separately"], hint: "", tag: null, needsQuantity: false },
    ],
    workIncluded: [

    ],
    exclusions: [

    ],
    responsibilityMatrix: [

    ],
  },
  {
    id: "gutters",
    name: "Gutters",
    code: "BRF-GUT",
    icon: "gutters",
    hasBidForm: true,
    standardNote: "",
    questions: [
      { id: "q1", label: "Gutter type", type: "select", options: ["K-Style", "Half-Round", "Box"], hint: "", tag: null, needsQuantity: false },
      { id: "q2", label: "Gutter size", type: "select", options: ["4\"", "5\"", "6\""], hint: "", tag: null, needsQuantity: false },
      { id: "q3", label: "Material", type: "select", options: ["Aluminum", "Copper", "Steel", "Vinyl"], hint: "", tag: null, needsQuantity: false },
      { id: "q4", label: "Color", type: "text", options: [], hint: "e.g. White / Musket Brown / Bronze", tag: null, needsQuantity: false },
      { id: "q5", label: "Downspout size", type: "select", options: ["2\"x3\"", "3\"x4\""], hint: "", tag: null, needsQuantity: false },
      { id: "q6", label: "Downspout quantity", type: "text", options: [], hint: "", tag: null, needsQuantity: false },
      { id: "q7", label: "Downspout discharge", type: "select", options: ["Grade", "Splash Block", "Underground Drainage"], hint: "", tag: null, needsQuantity: false },
      { id: "q8", label: "Gutter guards / leaf protection", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q9", label: "Underground drainage connection", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q10", label: "Linear footage estimated", type: "text", options: [], hint: "", tag: null, needsQuantity: false },
      { id: "q11", label: "Screened porch gutters", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q12", label: "Garage gutters", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
    ],
    workIncluded: [

    ],
    exclusions: [

    ],
    responsibilityMatrix: [

    ],
  },
  {
    id: "siding",
    name: "Siding",
    code: "BRF-SDG",
    icon: "siding",
    hasBidForm: true,
    standardNote: "",
    questions: [
      { id: "q1", label: "Siding type", type: "select", options: ["Fiber Cement HardiePlank", "LP SmartSide", "Vinyl", "Cedar", "Stucco", "Other"], hint: "", tag: null, needsQuantity: false },
      { id: "q2", label: "Brand / product line", type: "text", options: [], hint: "e.g. James Hardie HZ10", tag: null, needsQuantity: false },
      { id: "q3", label: "Profile / exposure", type: "text", options: [], hint: "e.g. 7\" lap / Dutch lap / Beaded", tag: null, needsQuantity: false },
      { id: "q4", label: "Thickness", type: "text", options: [], hint: "e.g. 5/16\"", tag: null, needsQuantity: false },
      { id: "q5", label: "Finish", type: "select", options: ["Pre-Painted", "Field Painted", "Primed Only"], hint: "", tag: null, needsQuantity: false },
      { id: "q6", label: "Color", type: "text", options: [], hint: "e.g. Arctic White", tag: null, needsQuantity: false },
      { id: "q7", label: "Trim type / material", type: "select", options: ["Same as Siding", "PVC Trim", "Cedar", "Composite", "Other"], hint: "", tag: null, needsQuantity: false },
      { id: "q8", label: "Trim brand / product", type: "text", options: [], hint: "e.g. Azek PVC", tag: null, needsQuantity: false },
      { id: "q9", label: "Trim thickness / profile", type: "text", options: [], hint: "e.g. 5/4 x 4", tag: null, needsQuantity: false },
      { id: "q10", label: "Corner boards", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q11", label: "Frieze board", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q12", label: "Belly band / water table", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q13", label: "Exterior window trim", type: "select", options: ["Yes All Windows", "Selected Only", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q14", label: "Exterior door trim", type: "select", options: ["Yes All Doors", "Selected Only", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q15", label: "Shutters", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q16", label: "Soffit", type: "select", options: ["Yes Included", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q17", label: "Soffit material", type: "select", options: ["Aluminum", "Vinyl", "Fiber Cement", "Match Siding"], hint: "", tag: null, needsQuantity: false },
      { id: "q18", label: "Vented soffit", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q19", label: "Fascia", type: "select", options: ["Yes Included", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q20", label: "Fascia material", type: "select", options: ["PVC", "Aluminum", "Match Trim"], hint: "", tag: null, needsQuantity: false },
      { id: "q21", label: "House wrap", type: "select", options: ["Yes Included", "No"], hint: "by framing sub", tag: null, needsQuantity: false },
      { id: "q22", label: "House wrap brand", type: "text", options: [], hint: "e.g. Tyvek HomeWrap", tag: null, needsQuantity: false },
      { id: "q23", label: "Tape all seams", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q24", label: "Number of stories", type: "select", options: ["1", "2", "3", "2.5 Cape Style"], hint: "", tag: null, needsQuantity: false },
      { id: "q25", label: "Gable ends included", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
      { id: "q26", label: "Screened porch siding", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q27", label: "Garage siding", type: "yn", options: ["Yes", "No"], hint: "", tag: "all_projects", needsQuantity: false },
    ],
    workIncluded: [

    ],
    exclusions: [

    ],
    responsibilityMatrix: [

    ],
  },
  {
    id: "masonry",
    name: "Masonry",
    code: "BRF-MAS",
    icon: "masonry",
    hasBidForm: true,
    standardNote: "",
    questions: [
      { id: "q1", label: "Primary material", type: "select", options: ["Full Brick", "Brick Veneer", "Natural Stone", "Cultured Stone", "CMU Block", "Stucco", "Other"], hint: "", tag: null, needsQuantity: false },
      { id: "q2", label: "Brand / product line", type: "text", options: [], hint: "e.g. Glen-Gery Brick", tag: null, needsQuantity: false },
      { id: "q3", label: "Color / finish", type: "text", options: [], hint: "e.g. Colonial Red", tag: null, needsQuantity: false },
      { id: "q4", label: "Mortar type", type: "select", options: ["Type S", "Type N", "Type M"], hint: "", tag: null, needsQuantity: false },
      { id: "q5", label: "Mortar color", type: "text", options: [], hint: "e.g. Gray / Buff / White", tag: null, needsQuantity: false },
      { id: "q6", label: "Joint profile", type: "select", options: ["Tooled", "Flush", "Struck", "Raked"], hint: "", tag: null, needsQuantity: false },
      { id: "q7", label: "Foundation veneer", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: true },
      { id: "q8", label: "Chimney", type: "yn", options: ["Yes", "No"], hint: "flues", tag: null, needsQuantity: true },
      { id: "q9", label: "Exterior fireplace", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q10", label: "Steps / stoops", type: "yn", options: ["Yes", "No"], hint: "& locations", tag: null, needsQuantity: true },
      { id: "q11", label: "Retaining walls", type: "yn", options: ["Yes", "No"], hint: "linear ft", tag: null, needsQuantity: true },
      { id: "q12", label: "Window sills", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q13", label: "Window wells", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q14", label: "Soldier course / accents", type: "yn", options: ["Yes", "No"], hint: "locations", tag: null, needsQuantity: false },
      { id: "q15", label: "Water table / belt course", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q16", label: "Supply responsibility", type: "select", options: ["Labor Only — PCG Supplies All", "Sub Supplies and Installs", "To Be Defined"], hint: "", tag: null, needsQuantity: false },
      { id: "q17", label: "Lintels", type: "select", options: ["PCG Provides", "Sub Provides", "N/A"], hint: "", tag: null, needsQuantity: false },
      { id: "q18", label: "Flashing at base", type: "select", options: ["Yes Included", "No"], hint: "by other trade", tag: null, needsQuantity: false },
      { id: "q19", label: "Weep holes", type: "select", options: ["Yes Included", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q20", label: "Sealer application", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q21", label: "Number of stories", type: "select", options: ["1", "2", "3", "2.5 Cape Style"], hint: "", tag: null, needsQuantity: false },
      { id: "q22", label: "Screened porch masonry", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
    ],
    workIncluded: [

    ],
    exclusions: [

    ],
    responsibilityMatrix: [

    ],
  },
  {
    id: "drywall",
    name: "Drywall",
    code: "BRF-DRY",
    icon: "drywall",
    hasBidForm: true,
    standardNote: "1/2\" main house, 5/8\" garage (fire rated), smooth finish Level 5.",
    questions: [
      { id: "q1", label: "Basement", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q2", label: "Screened porch", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q3", label: "Coffered ceilings", type: "yn", options: ["Yes", "No"], hint: "rooms", tag: null, needsQuantity: true },
      { id: "q4", label: "Tray ceilings", type: "yn", options: ["Yes", "No"], hint: "rooms", tag: null, needsQuantity: true },
      { id: "q5", label: "Curved walls", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q6", label: "Access panels", type: "yn", options: ["Yes", "No"], hint: "locations TBD on site", tag: null, needsQuantity: false },
      { id: "q7", label: "Materials supply", type: "select", options: ["Labor Only — PCG Supplies All", "Sub Supplies and Installs"], hint: "", tag: null, needsQuantity: false },
    ],
    workIncluded: [

    ],
    exclusions: [

    ],
    responsibilityMatrix: [

    ],
  },
  {
    id: "painting",
    name: "Painting",
    code: "BRF-PNT",
    icon: "painting",
    hasBidForm: true,
    standardNote: "Sub provides labor and materials. 5 colors per project. Scaffolding & step ladder by sub. Scope: interior walls, ceilings, trim, doors, closets, exterior body, trim, and doors. Caulking and primer included.",
    questions: [
      { id: "q1", label: "Garage interior", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q2", label: "Basement", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q3", label: "Screened porch", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q4", label: "Deck / porch floor", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q5", label: "Brand", type: "select", options: ["Benjamin Moore", "Sherwin-Williams", "Owner Specifies"], hint: "", tag: null, needsQuantity: false },
      { id: "q6", label: "Interior sheen walls", type: "select", options: ["Flat", "Eggshell", "Satin"], hint: "", tag: null, needsQuantity: false },
      { id: "q7", label: "Trim sheen", type: "select", options: ["Semi-Gloss", "Gloss"], hint: "", tag: null, needsQuantity: false },
      { id: "q8", label: "Exterior sheen", type: "select", options: ["Satin", "Semi-Gloss"], hint: "", tag: null, needsQuantity: false },
      { id: "q9", label: "Number of coats walls", type: "select", options: ["1", "2", "Primer + 2"], hint: "", tag: null, needsQuantity: false },
      { id: "q10", label: "Number of coats ceilings", type: "select", options: ["1", "2"], hint: "", tag: null, needsQuantity: false },
      { id: "q11", label: "Number of coats trim", type: "select", options: ["1", "2"], hint: "", tag: null, needsQuantity: false },
      { id: "q12", label: "Number of coats exterior", type: "select", options: ["1", "2"], hint: "", tag: null, needsQuantity: false },
    ],
    workIncluded: [

    ],
    exclusions: [

    ],
    responsibilityMatrix: [

    ],
  },
  {
    id: "tile",
    name: "Tile",
    code: "BRF-TIL",
    icon: "tile",
    hasBidForm: true,
    standardNote: "",
    questions: [
      { id: "q1", label: "Master bath floor", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q2", label: "Master shower walls & floor", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q3", label: "Secondary baths", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: true },
      { id: "q4", label: "Half baths", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: true },
      { id: "q5", label: "Kitchen backsplash", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q6", label: "Laundry room", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q7", label: "Entry foyer", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q8", label: "Mudroom", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q9", label: "Basement", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q10", label: "Fireplace surround", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q11", label: "Shower niches", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: true },
      { id: "q12", label: "Shower bench / seat", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: true },
      { id: "q13", label: "Linear drain", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q14", label: "Heated floor mat", type: "yn", options: ["Yes", "No"], hint: "which baths", tag: null, needsQuantity: false },
      { id: "q15", label: "Heated floor supply", type: "select", options: ["Sub Provides Labor and Materials"], hint: "", tag: null, needsQuantity: false },
      { id: "q16", label: "Tile supply", type: "select", options: ["PCG Supplies Tile — Sub Installs", "Sub Supplies and Installs"], hint: "", tag: null, needsQuantity: false },
      { id: "q17", label: "Waterproofing membrane", type: "select", options: ["Yes Sub Installs", "No"], hint: "by drywall sub", tag: null, needsQuantity: false },
      { id: "q18", label: "Grout sealing", type: "select", options: ["Yes Included", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q19", label: "Tile size", type: "select", options: ["Mosaic", "12x24", "24x48", "Large Format", "Mix"], hint: "", tag: null, needsQuantity: false },
      { id: "q20", label: "Natural stone", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
    ],
    workIncluded: [

    ],
    exclusions: [

    ],
    responsibilityMatrix: [

    ],
  },
  {
    id: "flooring",
    name: "Flooring",
    code: "BRF-FLR",
    icon: "flooring",
    hasBidForm: true,
    standardNote: "Labor only — PCG supplies all flooring materials.",
    questions: [
      { id: "q1", label: "Main living areas", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q2", label: "Bedrooms", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q3", label: "Stairs treads & risers", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q4", label: "Basement", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q5", label: "Screened porch", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q6", label: "Hardwood solid", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q7", label: "Engineered wood", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q8", label: "LVP / LVT", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q9", label: "Carpet", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q10", label: "Sand & finish hardwood on site", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q11", label: "Subfloor leveling / prep", type: "select", options: ["Included", "PCG to Authorize Separately"], hint: "", tag: null, needsQuantity: false },
      { id: "q12", label: "Transitions & thresholds", type: "yn", options: ["Yes"], hint: "included", tag: null, needsQuantity: false },
    ],
    workIncluded: [

    ],
    exclusions: [

    ],
    responsibilityMatrix: [

    ],
  },
  {
    id: "interior-trim",
    name: "Interior Trim",
    code: "BRF-TRM",
    icon: "trim",
    hasBidForm: true,
    standardNote: "Labor only — PCG provides all materials and fixtures. Scaffolding and step ladder by sub.",
    questions: [
      { id: "q1", label: "Base molding", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q2", label: "Door casing interior", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q3", label: "Window casing interior", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q4", label: "Crown molding", type: "yn", options: ["Yes", "No"], hint: "which rooms", tag: null, needsQuantity: false },
      { id: "q5", label: "Wainscoting", type: "yn", options: ["Yes", "No"], hint: "which rooms", tag: null, needsQuantity: false },
      { id: "q6", label: "Shoe molding / quarter round", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q7", label: "Install all interior doors", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q8", label: "Install door handles", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q9", label: "Install exterior door hardware", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q10", label: "Install garage door trim", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q11", label: "Stair treads & risers", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q12", label: "Newel posts", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q13", label: "Railings & balusters", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q14", label: "Install kitchen cabinets", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q15", label: "Install vanities", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q16", label: "Install cabinet & vanity pulls", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q17", label: "Closet shelving systems", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q18", label: "Closet rods & hardware", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q19", label: "Install bath hardware & fixtures", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q20", label: "TP holders towel bars robe hooks", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q21", label: "Shower glass clips towel bars", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q22", label: "Install medicine cabinets", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q23", label: "Install fireplace mantel", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q24", label: "Install floating shelves", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q25", label: "Install mirrors", type: "yn", options: ["Yes", "No"], hint: "", tag: null, needsQuantity: false },
      { id: "q26", label: "Attic access / pull down stair", type: "yn", options: ["Yes", "No"], hint: "", tag: "optional", needsQuantity: false },
      { id: "q27", label: "Countertops install", type: "yn", options: ["Yes"], hint: "included in trim scope", tag: null, needsQuantity: false },
      { id: "q28", label: "Windows & exterior doors install", type: "yn", options: ["Yes — Included in Trim Scope (exterior)", "Framing Scope"], hint: "", tag: null, needsQuantity: false },
    ],
    workIncluded: [

    ],
    exclusions: [

    ],
    responsibilityMatrix: [

    ],
  },
]
