ALTER TABLE forecast_machines
  ALTER COLUMN status DROP DEFAULT,
  ALTER COLUMN status TYPE BOOLEAN USING CASE WHEN status = 'scheduled' THEN TRUE ELSE FALSE END,
  ALTER COLUMN status SET DEFAULT FALSE;
