INSERT INTO ai_company_context (company, context, updated_at) VALUES

('framing', 'Premium Framing is responsible for the structural framing of residential construction projects, including walls, floors, and roof systems. The company executes wood framing work for additions and new builds, ensuring structural accuracy and alignment with architectural plans. It operates as a subcontractor within the Premium Group ecosystem, delivering framing services primarily to PCG-managed projects and external general contractors across New England. Revenue is driven by labor and material contracts tied to project milestones. Key financial indicators include labor cost per square foot, material waste ratios, and payment collection per phase. Projects are tracked through QuickBooks estimates tied to customer names (typically the homeowner or general contractor).', NOW()),

('hvac', 'Premium HVAC delivers heating and ventilation systems designed to support comfort and efficiency in residential buildings. The company handles system installation and maintenance, working alongside construction teams to ensure proper integration throughout the project lifecycle. It operates under service contracts and project-based work, often coordinated with Premium Framing and PCG timelines. Revenue includes both installation contracts and recurring maintenance calls. Key financial metrics include billable hours, equipment procurement margins, and warranty service costs. Projects are tracked through QuickBooks estimates and invoices linked to homeowners and general contractors.', NOW()),

('pcg', 'Premium Contractors Group (PCG) operates as a general contracting company, managing renovations, additions, and new construction projects across Massachusetts. PCG oversees project execution, coordinating trades, timelines, and on-site activities to ensure consistent delivery from planning through completion. As the primary client-facing entity of Premium Group Inc, PCG manages the largest revenue volume. It coordinates work with Premium Framing, Premium HVAC, and external subcontractors. Key financial metrics include project gross margin, subcontractor cost control, change order frequency, and invoice-to-payment cycles. Projects span from small renovations to multi-hundred-thousand-dollar new builds, tracked through QuickBooks estimates and customer invoices.', NOW())

ON CONFLICT (company) DO UPDATE SET context = EXCLUDED.context, updated_at = NOW();
