DROP TABLE IF EXISTS monthly_execution_history;
DROP TABLE IF EXISTS operational_forecast_index;
DROP TABLE IF EXISTS c_machine_provider;
DROP TABLE IF EXISTS c_contract_steps;
DROP TABLE IF EXISTS c_machines;
DROP TABLE IF EXISTS c_fieldwire;
DROP TABLE IF EXISTS c_workforce;
DROP TABLE IF EXISTS forecast_contract_steps;
DROP TABLE IF EXISTS forecast_machines;
DROP TABLE IF EXISTS forecast_fieldwire;
ALTER TABLE forecast_projects DROP COLUMN IF EXISTS previous_end_date;
ALTER TABLE forecast_projects DROP COLUMN IF EXISTS previous_start_date;
ALTER TABLE forecast_projects DROP COLUMN IF EXISTS previous_beams_date;
ALTER TABLE forecast_projects DROP COLUMN IF EXISTS machine_provider;
ALTER TABLE forecast_projects DROP COLUMN IF EXISTS storage;
ALTER TABLE forecast_projects DROP COLUMN IF EXISTS buildertrend;
ALTER TABLE forecast_projects DROP COLUMN IF EXISTS hvac;
ALTER TABLE forecast_projects DROP COLUMN IF EXISTS obs;
ALTER TABLE forecast_projects DROP COLUMN IF EXISTS address;
ALTER TABLE forecast_projects DROP COLUMN IF EXISTS lote_bld;
ALTER TABLE forecast_projects DROP COLUMN IF EXISTS type;
ALTER TABLE forecast_projects DROP COLUMN IF EXISTS job_site;
ALTER TABLE forecast_projects DROP COLUMN IF EXISTS cliente;
