-- Controle de Permit da HVAC.
--
-- O ciclo do Permit tem três marcos, e nenhum deles é data: o que importa é se
-- já foi feito ou não. Por isso a tabela espelha forecast_fieldwire — uma linha
-- por obra por etapa, com status textual — e não as colunas de data das quatro
-- etapas de obra da HVAC.
--
--   1. Manual J             → cálculo de carga térmica
--   2. Application Submitted → aplicação protocolada na cidade
--   3. Permit Approved      → alvará emitido
--
-- É exclusivo da HVAC. A Framing não tem etapa de Permit, então obra dessa
-- empresa nunca recebe linha aqui — e o alerta que lê esta tabela nunca a vê.
CREATE TABLE IF NOT EXISTS forecast_permit (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT        NOT NULL,
    step       TEXT        NOT NULL,
    -- Mesmo vocabulário do Fieldwire: NULL = pendente, 'completed' = feito,
    -- 'dispensed' = não se aplica a esta obra.
    status     TEXT,
    -- A ordem é do processo, não alfabética: Manual J vem antes da aplicação,
    -- que vem antes da aprovação. Sem isso a lista sairia embaralhada.
    position   SMALLINT    NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (project_id, step)
);

CREATE INDEX IF NOT EXISTS idx_forecast_permit_project ON forecast_permit (project_id);

-- ── Backfill ────────────────────────────────────────────────────────────────
-- Toda obra da HVAC que já existe passa a ter as três etapas, pendentes. Sem
-- isso, o controle só valeria para obra criada de hoje em diante, e as 246 que
-- entraram na carga do dia 21 ficariam de fora do alerta.
INSERT INTO forecast_permit (project_id, step, status, position)
SELECT c.id, s.step, NULL, s.position
FROM forecast_core c
CROSS JOIN (VALUES
    ('Manual J', 1),
    ('Application Submitted', 2),
    ('Permit Approved', 3)
) AS s(step, position)
WHERE LOWER(COALESCE(c.company, '')) = 'hvac'
ON CONFLICT (project_id, step) DO NOTHING;
