// Mock data for testing pages without real API data

import type { ForecastProject } from "@bor2/shared"
import type { TakeoffWork } from "@/services/takeoff.service"

export const MOCK_FORECAST_PROJECTS: ForecastProject[] = [
  // January 2025
  {
    id: "1",
    company: "framing",
    name: "Orchard Hills Ph.1 – Lot 12",
    cliente: "Orchard Hills Development",
    jobSite: "Orchard Hills Ph.1",
    type: "SFR",
    loteBld: "Lot 12",
    address: "482 Orchard Dr, Irvine, CA 92618",
    obs: "Steel beam delivery pending confirmation",
    status: "completed",
    startDate: new Date(2025, 0, 6).toISOString(),
    endDate: new Date(2025, 0, 31).toISOString(),
    contractValue: 82000,
    team: "Team Alpha",
    qbTime: true,
    hvac: false,
    buildertrend: true,
    storage: true,
    machineProvider: "Sunbelt Rentals",
    previousBeamsDate: new Date(2025, 0, 3).toISOString(),
    previousStartDate: null,
    previousEndDate: null,
    fieldwire: [
      { id: 1, status: true },
      { id: 2, status: true },
      { id: 3, status: true },
    ],
    machines: [
      { id: 1, title: "Boom Lift", status: "dispensed" },
      { id: 2, title: "Forklift", status: "dispensed" },
    ],
    contractSteps: [
      { id: 1, team: "Team Alpha", step: "Foundation", status: "true" },
      { id: 2, team: "Team Alpha", step: "Framing", status: "true" },
      { id: 3, team: "Team Alpha", step: "Inspection", status: "true" },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    company: "framing",
    name: "Westview Estates – Lot 7",
    cliente: "Westview Homes LLC",
    jobSite: "Westview Estates",
    type: "SFR",
    loteBld: "Lot 7",
    address: "1110 Westview Blvd, Anaheim, CA 92801",
    obs: "",
    status: "completed",
    startDate: new Date(2025, 0, 13).toISOString(),
    endDate: new Date(2025, 1, 14).toISOString(),
    contractValue: 95000,
    team: "Team Beta",
    qbTime: true,
    hvac: false,
    buildertrend: true,
    storage: false,
    machineProvider: "",
    previousBeamsDate: null,
    previousStartDate: null,
    previousEndDate: null,
    fieldwire: [
      { id: 4, status: true },
      { id: 5, status: false },
    ],
    machines: [
      { id: 3, title: "Boom Lift", status: "scheduled" },
    ],
    contractSteps: [
      { id: 4, team: "Team Beta", step: "Foundation", status: "true" },
      { id: 5, team: "Team Beta", step: "Framing", status: null },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // February 2025
  {
    id: "3",
    company: "framing",
    name: "Summit Ridge – Lot 3A",
    cliente: "Summit Ridge Builders",
    jobSite: "Summit Ridge",
    type: "Townhouse",
    loteBld: "Lot 3A",
    address: "230 Summit Ln, Riverside, CA 92501",
    obs: "Revised structural drawings received 02/05",
    status: "completed",
    startDate: new Date(2025, 1, 3).toISOString(),
    endDate: new Date(2025, 1, 28).toISOString(),
    contractValue: 67000,
    team: "Team Alpha",
    qbTime: false,
    hvac: false,
    buildertrend: true,
    storage: true,
    machineProvider: "BlueLine Rental",
    previousBeamsDate: new Date(2025, 0, 30).toISOString(),
    previousStartDate: null,
    previousEndDate: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    company: "hvac",
    name: "Parkside Commons HVAC",
    cliente: "Parkside Development",
    jobSite: "Parkside Commons",
    type: "Multi-Family",
    loteBld: "Building C",
    address: "800 Parkside Ave, Santa Ana, CA 92701",
    obs: "",
    status: "completed",
    startDate: new Date(2025, 1, 10).toISOString(),
    endDate: new Date(2025, 2, 15).toISOString(),
    contractValue: 145000,
    team: "HVAC Team 1",
    qbTime: true,
    hvac: true,
    buildertrend: false,
    storage: false,
    machineProvider: "",
    previousBeamsDate: null,
    previousStartDate: null,
    previousEndDate: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // March 2025
  {
    id: "5",
    company: "framing",
    name: "Crestline Reserve – Lot 22",
    cliente: "Crestline Reserve HOA",
    jobSite: "Crestline Reserve",
    type: "SFR",
    loteBld: "Lot 22",
    address: "5520 Crestline Rd, Corona, CA 92880",
    obs: "",
    status: "active",
    startDate: new Date(2025, 2, 3).toISOString(),
    endDate: new Date(2025, 3, 25).toISOString(),
    contractValue: 88000,
    team: "Team Beta",
    qbTime: true,
    hvac: false,
    buildertrend: true,
    storage: true,
    machineProvider: "Sunbelt Rentals",
    previousBeamsDate: new Date(2025, 1, 28).toISOString(),
    previousStartDate: null,
    previousEndDate: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    company: "framing",
    name: "Heritage Pointe – Lot 8",
    cliente: "Heritage Homes Inc.",
    jobSite: "Heritage Pointe",
    type: "SFR",
    loteBld: "Lot 8",
    address: "120 Heritage Way, Chino Hills, CA 91709",
    obs: "HOA pre-inspection required prior to sheathing",
    status: "active",
    startDate: new Date(2025, 2, 17).toISOString(),
    endDate: new Date(2025, 4, 2).toISOString(),
    contractValue: 102000,
    team: "Team Alpha",
    qbTime: true,
    hvac: false,
    buildertrend: true,
    storage: false,
    machineProvider: "",
    previousBeamsDate: null,
    previousStartDate: null,
    previousEndDate: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    company: "pcg",
    name: "Downtown Commerce Center",
    cliente: "Metro Commercial Group",
    jobSite: "Downtown Commerce Center",
    type: "Commercial",
    loteBld: "Phase 2",
    address: "300 Commerce St, Los Angeles, CA 90012",
    obs: "Permit 2025-LA-04421 approved",
    status: "cancelled",
    startDate: new Date(2025, 2, 10).toISOString(),
    endDate: new Date(2025, 5, 30).toISOString(),
    contractValue: 420000,
    team: "PCG Team",
    qbTime: true,
    hvac: false,
    buildertrend: false,
    storage: false,
    machineProvider: "",
    previousBeamsDate: null,
    previousStartDate: null,
    previousEndDate: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // April 2025
  {
    id: "8",
    company: "framing",
    name: "Lakewood Terrace – Lot 15",
    cliente: "Lakewood Terrace Partners",
    jobSite: "Lakewood Terrace",
    type: "SFR",
    loteBld: "Lot 15",
    address: "710 Lakewood Dr, Fontana, CA 92335",
    obs: "",
    status: "planned",
    startDate: new Date(2025, 3, 7).toISOString(),
    endDate: new Date(2025, 4, 16).toISOString(),
    contractValue: 79000,
    team: "",
    qbTime: false,
    hvac: false,
    buildertrend: false,
    storage: false,
    machineProvider: "",
    previousBeamsDate: new Date(2025, 3, 4).toISOString(),
    previousStartDate: null,
    previousEndDate: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "9",
    company: "framing",
    name: "Vineyard Walk – Lot 31",
    cliente: "Vineyard Walk LLC",
    jobSite: "Vineyard Walk",
    type: "SFR",
    loteBld: "Lot 31",
    address: "990 Vine St, Temecula, CA 92590",
    obs: "Material delivery split into 2 phases",
    status: "planned",
    startDate: new Date(2025, 3, 21).toISOString(),
    endDate: new Date(2025, 5, 6).toISOString(),
    contractValue: 91000,
    team: "Team Beta",
    qbTime: false,
    hvac: false,
    buildertrend: true,
    storage: true,
    machineProvider: "Home Depot Pro",
    previousBeamsDate: null,
    previousStartDate: null,
    previousEndDate: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "10",
    company: "hvac",
    name: "Redwood Villas HVAC",
    cliente: "Redwood Property Group",
    jobSite: "Redwood Villas",
    type: "Multi-Family",
    loteBld: "Units 1–20",
    address: "2250 Redwood Ave, Murrieta, CA 92562",
    obs: "",
    status: "planned",
    startDate: new Date(2025, 3, 14).toISOString(),
    endDate: new Date(2025, 6, 31).toISOString(),
    contractValue: 210000,
    team: "HVAC Team 2",
    qbTime: true,
    hvac: true,
    buildertrend: true,
    storage: false,
    machineProvider: "",
    previousBeamsDate: null,
    previousStartDate: null,
    previousEndDate: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const MOCK_TAKEOFFS: TakeoffWork[] = [
  {
    id: "t1",
    project: "Orchard Hills Phase 1",
    modeloDaCasa: "Model A",
    description: "Framing takeoff for Phase 1 residential units",
    docLinks: "https://drive.google.com/file/d/example1",
    dataSolicitacao: new Date(2025, 2, 5).toISOString().split("T")[0],
    dataInicio: new Date(2025, 2, 10).toISOString().split("T")[0],
    dataEstimadaEntrega: new Date(2025, 3, 5).toISOString().split("T")[0],
    entregaReal: new Date(2025, 3, 3).toISOString().split("T")[0],
    stageDwg: "ok",
    stageMitek3d: "ok",
    stageMaterialsList: "ok",
    stagePanelDivision: "in-progress",
    stageValidation: "pending",
    stageCutList: "pending",
    stageProduction: "pending",
    stageDelivery: "pending",
    stageAssembly: "pending",
    createdAt: new Date().toISOString(),
  },
  {
    id: "t2",
    project: "Summit Plaza HVAC",
    modeloDaCasa: "Model B",
    description: "HVAC system takeoff and material estimate",
    docLinks: "https://drive.google.com/file/d/example2",
    dataSolicitacao: new Date(2025, 4, 1).toISOString().split("T")[0],
    dataInicio: new Date(2025, 4, 10).toISOString().split("T")[0],
    dataEstimadaEntrega: new Date(2025, 5, 10).toISOString().split("T")[0],
    entregaReal: null,
    stageDwg: "ok",
    stageMitek3d: "in-progress",
    stageMaterialsList: "pending",
    stagePanelDivision: "pending",
    stageValidation: "pending",
    stageCutList: "pending",
    stageProduction: "pending",
    stageDelivery: "pending",
    stageAssembly: "pending",
    createdAt: new Date().toISOString(),
  },
]

export const MOCK_INVENTORY = {
  consumo_vs_limite: [
    {
      project_id: "p1",
      project_nome: "Orchard Hills",
      house_model_id: "m1",
      house_model_nome: "Model A",
      product_id: "prod1",
      product_nome: "Lumber 2x4",
      unidade_medida: "pcs",
      quantidade_limite: 500,
      quantidade_consumida: 425,
      percentual_consumido: 85,
      limite_excedido: false,
    },
    {
      project_id: "p1",
      project_nome: "Orchard Hills",
      house_model_id: "m1",
      house_model_nome: "Model A",
      product_id: "prod2",
      product_nome: "Plywood 3/4",
      unidade_medida: "sheets",
      quantidade_limite: 200,
      quantidade_consumida: 215,
      percentual_consumido: 107.5,
      limite_excedido: true,
    },
  ],
  historico_saldo: [
    {
      mes: "2025-03",
      product_id: "prod1",
      product_nome: "Lumber 2x4",
      saldo_minimo: 100,
      saldo_acumulado: 285,
      abaixo_minimo: false,
    },
  ],
  detalhes_excesso: [
    {
      project_id: "p1",
      project_nome: "Orchard Hills",
      house_model_nome: "Model A",
      product_id: "prod2",
      product_nome: "Plywood 3/4",
      usuario_responsavel: "John Smith",
      movement_date: "2025-03-15",
      quantidade_retirada: 15,
      quantidade_limite: 200,
      consumo_acumulado_momento: 215,
      excedeu_neste_momento: true,
      valor_unitario: 25.5,
    },
  ],
  gastos_usuario: [
    {
      usuario_id: "u1",
      usuario_nome: "John Smith",
      role: "manager",
      mes: "2025-03",
      total_retiradas: 45,
      valor_total_retirado: 5432.5,
    },
  ],
  product_prices: {
    prod1: 12.5,
    prod2: 25.5,
  },
}
