// Mock data for testing pages without real API data

import type { ForecastProject } from "@bor2/shared"
import type { TakeoffWork } from "@/services/takeoff.service"

export const MOCK_FORECAST_PROJECTS: ForecastProject[] = [
  {
    id: "1",
    company: "framing",
    name: "Orchard Hills Phase 1",
    status: "active",
    startDate: new Date(2025, 2, 1).toISOString(),
    endDate: new Date(2025, 7, 31).toISOString(),
    contractValue: 250000,
    team: "Team Alpha",
    qbTime: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    company: "hvac",
    name: "Summit Plaza HVAC",
    status: "planned",
    startDate: new Date(2025, 5, 1).toISOString(),
    endDate: new Date(2025, 10, 30).toISOString(),
    contractValue: 180000,
    team: "HVAC Team",
    qbTime: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    company: "pcg",
    name: "Downtown Commerce Center",
    status: "completed",
    startDate: new Date(2024, 6, 1).toISOString(),
    endDate: new Date(2025, 1, 28).toISOString(),
    contractValue: 420000,
    team: "PCG Team",
    qbTime: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const MOCK_TAKEOFFS: TakeoffWork[] = [
  {
    id: "t1",
    project: "Orchard Hills Phase 1",
    modeloDaCasa: "Model A",
    description: "Framing takeoff for Phase 1 residential units",
    docLinks: "https://drive.google.com/file/d/example1",
    dataSolicitacao: new Date(2025, 2, 5).toISOString().split("T")[0],
    dataInicio: new Date(2025, 2, 10).toISOString().split("T")[0],
    dataEstimadaEntrega: new Date(2025, 3, 5).toISOString().split("T")[0],
    entregaReal: new Date(2025, 3, 3).toISOString().split("T")[0],
    stageDwg: "ok",
    stageMitek3d: "ok",
    stageMaterialsList: "ok",
    stagePanelDivision: "in-progress",
    stageValidation: "pending",
    stageCutList: "pending",
    stageProduction: "pending",
    stageDelivery: "pending",
    stageAssembly: "pending",
    createdAt: new Date().toISOString(),
  },
  {
    id: "t2",
    project: "Summit Plaza HVAC",
    modeloDaCasa: "Model B",
    description: "HVAC system takeoff and material estimate",
    docLinks: "https://drive.google.com/file/d/example2",
    dataSolicitacao: new Date(2025, 4, 1).toISOString().split("T")[0],
    dataInicio: new Date(2025, 4, 10).toISOString().split("T")[0],
    dataEstimadaEntrega: new Date(2025, 5, 10).toISOString().split("T")[0],
    entregaReal: null,
    stageDwg: "ok",
    stageMitek3d: "in-progress",
    stageMaterialsList: "pending",
    stagePanelDivision: "pending",
    stageValidation: "pending",
    stageCutList: "pending",
    stageProduction: "pending",
    stageDelivery: "pending",
    stageAssembly: "pending",
    createdAt: new Date().toISOString(),
  },
]

export const MOCK_INVENTORY = {
  consumo_vs_limite: [
    {
      project_id: "p1",
      project_nome: "Orchard Hills",
      house_model_id: "m1",
      house_model_nome: "Model A",
      product_id: "prod1",
      product_nome: "Lumber 2x4",
      unidade_medida: "pcs",
      quantidade_limite: 500,
      quantidade_consumida: 425,
      percentual_consumido: 85,
      limite_excedido: false,
    },
    {
      project_id: "p1",
      project_nome: "Orchard Hills",
      house_model_id: "m1",
      house_model_nome: "Model A",
      product_id: "prod2",
      product_nome: "Plywood 3/4",
      unidade_medida: "sheets",
      quantidade_limite: 200,
      quantidade_consumida: 215,
      percentual_consumido: 107.5,
      limite_excedido: true,
    },
  ],
  historico_saldo: [
    {
      mes: "2025-03",
      product_id: "prod1",
      product_nome: "Lumber 2x4",
      saldo_minimo: 100,
      saldo_acumulado: 285,
      abaixo_minimo: false,
    },
  ],
  detalhes_excesso: [
    {
      project_id: "p1",
      project_nome: "Orchard Hills",
      house_model_nome: "Model A",
      product_id: "prod2",
      product_nome: "Plywood 3/4",
      usuario_responsavel: "John Smith",
      movement_date: "2025-03-15",
      quantidade_retirada: 15,
      quantidade_limite: 200,
      consumo_acumulado_momento: 215,
      excedeu_neste_momento: true,
      valor_unitario: 25.5,
    },
  ],
  gastos_usuario: [
    {
      usuario_id: "u1",
      usuario_nome: "John Smith",
      role: "manager",
      mes: "2025-03",
      total_retiradas: 45,
      valor_total_retirado: 5432.5,
    },
  ],
  product_prices: {
    prod1: 12.5,
    prod2: 25.5,
  },
}
